apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterstack-operator
  namespace: system
  labels:
    app.kubernetes.io/name: betterstack-operator
    app.kubernetes.io/part-of: betterstack-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: betterstack-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: betterstack-operator
        app.kubernetes.io/part-of: betterstack-operator
    spec:
      serviceAccountName: betterstack-operator
      containers:
        - name: manager
          image: ghcr.io/loks0n/betterstack-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
