image:
  repository: ghcr.io/loks0n/betterstack-operator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

namespace: ""

replicaCount: 1

podAnnotations: {}
podLabels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

podSecurityContext: {}

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65532

nodeSelector: {}

tolerations: []

affinity: {}

manager:
  leaderElection: true
  metricsPort: 8080
  healthProbePort: 8081
  extraArgs: []

rbac:
  create: true

crds:
  install: true

credentials:
  existingSecret: ""
  secret:
    create: false
    name: ""
    key: api-key
    value: ""
    annotations: {}
    namespace: ""
    additionalNamespaces: []
