image:
  repository: ghcr.io/loks0n/betterstack-operator
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

namespace: ""

replicaCount: 1

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

manager:
  leaderElection: true
  metricsPort: 8443
  healthProbePort: 8081
  extraArgs: []

rbac:
  create: true

crds:
  install: true
