apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: betterstackheartbeats.monitoring.betterstack.io
spec:
  group: monitoring.betterstack.io
  names:
    kind: BetterStackHeartbeat
    listKind: BetterStackHeartbeatList
    plural: betterstackheartbeats
    singular: betterstackheartbeat
    shortNames:
      - bsheartbeat
      - bsh
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: ID
          type: string
          jsonPath: .status.heartbeatID
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - periodSeconds
                - apiTokenSecretRef
              properties:
                name:
                  type: string
                periodSeconds:
                  type: integer
                  minimum: 1
                graceSeconds:
                  type: integer
                  minimum: 0
                teamName:
                  type: string
                call:
                  type: boolean
                sms:
                  type: boolean
                email:
                  type: boolean
                push:
                  type: boolean
                criticalAlert:
                  type: boolean
                teamWaitSeconds:
                  type: integer
                  minimum: 0
                heartbeatGroupID:
                  type: integer
                  minimum: 0
                sortIndex:
                  type: integer
                paused:
                  type: boolean
                maintenanceDays:
                  type: array
                  items:
                    type: string
                maintenanceFrom:
                  type: string
                maintenanceTo:
                  type: string
                maintenanceTimezone:
                  type: string
                policyID:
                  type: string
                baseURL:
                  type: string
                  format: uri
                apiTokenSecretRef:
                  type: object
                  default:
                    name: betterstack-operator-credentials
                    key: api-key
                  required:
                    - name
                    - key
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                    optional:
                      type: boolean
            status:
              type: object
              properties:
                heartbeatID:
                  type: string
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - reason
                      - message
                      - lastTransitionTime
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                lastSyncedTime:
                  type: string
                  format: date-time
