apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: betterstackmonitors.monitoring.betterstack.io
spec:
  group: monitoring.betterstack.io
  names:
    kind: BetterStackMonitor
    listKind: BetterStackMonitorList
    plural: betterstackmonitors
    singular: betterstackmonitor
    shortNames:
      - bsmonitor
      - bsm
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: ID
          type: string
          jsonPath: .status.monitorID
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - url
                - apiTokenSecretRef
              properties:
                url:
                  type: string
                  minLength: 1
                name:
                  type: string
                monitorType:
                  type: string
                  enum:
                    - status
                    - expected_status_code
                    - keyword
                    - keyword_absence
                    - ping
                    - tcp
                    - udp
                    - smtp
                    - pop
                    - imap
                    - dns
                    - playwright
                teamName:
                  type: string
                checkFrequencyMinutes:
                  type: integer
                  minimum: 1
                regions:
                  type: array
                  items:
                    type: string
                requestMethod:
                  type: string
                  description: HTTP method used for the check
                  enum:
                    - get
                    - post
                    - put
                    - patch
                    - delete
                    - head
                    - options
                    - trace
                expectedStatusCode:
                  type: integer
                  minimum: 100
                  maximum: 599
                expectedStatusCodes:
                  type: array
                  items:
                    type: integer
                    minimum: 100
                    maximum: 599
                requiredKeyword:
                  type: string
                paused:
                  type: boolean
                email:
                  type: boolean
                sms:
                  type: boolean
                call:
                  type: boolean
                push:
                  type: boolean
                criticalAlert:
                  type: boolean
                followRedirects:
                  type: boolean
                verifySSL:
                  type: boolean
                rememberCookies:
                  type: boolean
                policyID:
                  type: string
                expirationPolicyID:
                  type: string
                monitorGroupID:
                  type: string
                teamWaitSeconds:
                  type: integer
                  minimum: 0
                domainExpirationDays:
                  type: integer
                  minimum: 0
                sslExpirationDays:
                  type: integer
                  minimum: 0
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                requestTimeoutSeconds:
                  type: integer
                  minimum: 0
                recoveryPeriodSeconds:
                  type: integer
                  minimum: 0
                confirmationPeriodSeconds:
                  type: integer
                  minimum: 0
                ipVersion:
                  type: string
                  enum:
                    - ipv4
                    - ipv6
                maintenanceDays:
                  type: array
                  items:
                    type: string
                    enum:
                      - mon
                      - tue
                      - wed
                      - thu
                      - fri
                      - sat
                      - sun
                maintenanceFrom:
                  type: string
                maintenanceTo:
                  type: string
                maintenanceTimezone:
                  type: string
                requestHeaders:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        minLength: 1
                      value:
                        type: string
                        minLength: 1
                    required:
                      - name
                      - value
                requestBody:
                  type: string
                authUsername:
                  type: string
                authPassword:
                  type: string
                environmentVariables:
                  type: object
                  additionalProperties:
                    type: string
                playwrightScript:
                  type: string
                scenarioName:
                  type: string
                additionalAttributes:
                  type: object
                  additionalProperties:
                    type: string
                baseURL:
                  type: string
                  format: uri
                apiTokenSecretRef:
                  type: object
                  default:
                    name: betterstack-operator-credentials
                    key: api-key
                  required:
                    - name
                    - key
                  properties:
                    name:
                      type: string
                      minLength: 1
                    key:
                      type: string
                      minLength: 1
            status:
              type: object
              properties:
                monitorID:
                  type: string
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - reason
                      - message
                      - lastTransitionTime
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                lastSyncedTime:
                  type: string
                  format: date-time
      subresources:
        status: {}
