apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "betterstack-operator.fullname" . }}
  namespace: {{ include "betterstack-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "betterstack-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "betterstack-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "betterstack-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}{{ toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ default (include "betterstack-operator.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--leader-elect={{ .Values.manager.leaderElection }}"
            - "--metrics-bind-address=:{{ .Values.manager.metricsPort }}"
            - "--health-probe-bind-address=:{{ .Values.manager.healthProbePort }}"
            {{- range $arg := .Values.manager.extraArgs }}
            - {{ $arg | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.manager.metricsPort }}
            - name: healthz
              containerPort: {{ .Values.manager.healthProbePort }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          {{- with .Values.containerSecurityContext }}
          securityContext:
{{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
