{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "betterstack-operator.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ include "betterstack-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "betterstack-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
