name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify formatting
        run: |
          if [ -n "$(gofmt -l $(find . -name '*.go'))" ]; then
            echo "Go files are not formatted"
            exit 1
          fi

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...

  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --file Dockerfile --tag betterstack-operator:test .

  e2e:
    name: End-to-End
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install kind
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0
          cluster_name: betterstack-e2e

      - name: Run e2e
        env:
          KIND_CLUSTER_NAME: betterstack-e2e
          BETTERSTACK_TOKEN: ${{ secrets.BETTERSTACK_TOKEN }}
        run: |
          if [ -z "$BETTERSTACK_TOKEN" ]; then
            echo "BETTERSTACK_TOKEN secret not set; failing"
            exit 1
          fi
          go test -tags=e2e ./test/e2e -run TestBetterStackMonitorLifecycle -timeout 20m
